{
  programs.git = {
    enable = true;
    userName = "Max Clarke";
    userEmail = "maxeonyx@gmail.com";
    # Global git ignore file contents (placed in .config/git/ignore)
    # These are files which, in principle, I might create but another person
    # editing the same repository might *not* create.
    #
    # If a file would be created no matter who was developing, then it should
    # be in the project .gitignore. For example, __pycache__/ directories will
    # always be present when importing a python module, no matter what system
    # or editor one is using.
    ignores = [
      "# Generated by home-manager"
      "# Linux"
      "*~"
      ".fuse_hidden*"
      ".directory"
      ".Trash-*"
      ".nfs*"
      
      "# Windows"
      "Thumbs.db"
      "Thumbs.db:encryptable"
      "ehthumbs.db"
      "ehthumbs_vista.db"
      "*.stackdump"
      "[Dd]esktop.ini"
      "$RECYCLE.BIN/"
      "*.msi"
      "*.msix"
      "*.lnk"
      
      "# VS Code"
      ".vscode/*"
      "!.vscode/settings.json"
      "!.vscode/tasks.json"
      "!.vscode/launch.json"
      "!.vscode/extensions.json"
      "!.vscode/*.code-snippets"
    ];
    iniContent.init.defaultBranch = "main";
  };
}
      
